"""Controls page for Reel Forge video configuration."""
from PySide6.QtWidgets import QWidget, QVBoxLayout, QHBoxLayout, QLabel, QPushButton, QComboBox, QSpinBox, QFrame
from src.theme import TITLE_STYLE, SUBTITLE_STYLE, SECTION_TITLE_STYLE, BIG_BUTTON_STYLE, CARD_STYLE, INPUT_STYLE


class ControlsPage(QWidget):
    def __init__(self, client, parent=None):
        super().__init__(parent)
        self._client = client
        layout = QVBoxLayout(self)
        layout.setContentsMargins(32, 24, 32, 24)
        layout.setSpacing(24)
        header = QLabel("Controls")
        header.setStyleSheet(TITLE_STYLE)
        layout.addWidget(header)
        desc = QLabel("Configure encode/decode parameters.")
        desc.setStyleSheet(SUBTITLE_STYLE)
        layout.addWidget(desc)

        frame = QFrame()
        frame.setStyleSheet(CARD_STYLE)
        fl = QVBoxLayout(frame)
        fl.setSpacing(12)
        fl.addWidget(QLabel("Video Configuration"))
        fl.itemAt(fl.count()-1).widget().setStyleSheet(SECTION_TITLE_STYLE)

        row1 = QHBoxLayout()
        row1.addWidget(QLabel("Codec:"))
        self.codec_cb = QComboBox()
        self.codec_cb.addItems(["H.264", "H.265", "AV1"])
        self.codec_cb.setStyleSheet(INPUT_STYLE)
        row1.addWidget(self.codec_cb)
        row1.addStretch()
        fl.addLayout(row1)

        row2 = QHBoxLayout()
        row2.addWidget(QLabel("Resolution:"))
        self.width_sb = QSpinBox()
        self.width_sb.setRange(320, 7680)
        self.width_sb.setValue(1920)
        self.width_sb.setStyleSheet(INPUT_STYLE)
        row2.addWidget(self.width_sb)
        row2.addWidget(QLabel("x"))
        self.height_sb = QSpinBox()
        self.height_sb.setRange(240, 4320)
        self.height_sb.setValue(1080)
        self.height_sb.setStyleSheet(INPUT_STYLE)
        row2.addWidget(self.height_sb)
        row2.addStretch()
        fl.addLayout(row2)

        row3 = QHBoxLayout()
        row3.addWidget(QLabel("Bitrate:"))
        self.bitrate_sb = QSpinBox()
        self.bitrate_sb.setRange(100000, 200000000)
        self.bitrate_sb.setValue(10000000)
        self.bitrate_sb.setSingleStep(1000000)
        self.bitrate_sb.setStyleSheet(INPUT_STYLE)
        row3.addWidget(self.bitrate_sb)
        row3.addWidget(QLabel("bps"))
        row3.addStretch()
        fl.addLayout(row3)

        btn_row = QHBoxLayout()
        self.encode_btn = QPushButton("Start Encode")
        self.encode_btn.setStyleSheet(BIG_BUTTON_STYLE)
        self.encode_btn.clicked.connect(lambda: self._client.start_encode(self.codec_cb.currentIndex(), self.width_sb.value(), self.height_sb.value(), self.bitrate_sb.value()))
        btn_row.addWidget(self.encode_btn)
        self.decode_btn = QPushButton("Start Decode")
        self.decode_btn.setStyleSheet(f"QPushButton {{background: #388E3C; color: white; border: none; border-radius: 12px; padding: 16px 32px; font-size: 15px; font-weight: 600; min-width: 180px; min-height: 48px;}} QPushButton:hover {{background: #2E7D32;}}")
        self.decode_btn.clicked.connect(lambda: self._client.start_decode(self.codec_cb.currentIndex(), self.width_sb.value(), self.height_sb.value()))
        btn_row.addWidget(self.decode_btn)
        btn_row.addStretch()
        fl.addLayout(btn_row)
        layout.addWidget(frame)
        layout.addStretch()
