# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: reel_forge.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='reel_forge.proto',
  package='reelforge',
  syntax='proto3',
  serialized_pb=_b('\n\x10reel_forge.proto\x12\treelforge\"Z\n\x0c\x45ncodeConfig\x12\r\n\x05\x63odec\x18\x01 \x01(\r\x12\r\n\x05width\x18\x02 \x01(\r\x12\x0e\n\x06height\x18\x03 \x01(\r\x12\x0f\n\x07\x62itrate\x18\x04 \x01(\r\x12\x0b\n\x03\x66ps\x18\x05 \x01(\r\"<\n\x0c\x44\x65\x63odeConfig\x12\r\n\x05\x63odec\x18\x01 \x01(\r\x12\r\n\x05width\x18\x02 \x01(\r\x12\x0e\n\x06height\x18\x03 \x01(\r\"\x1c\n\nJobRequest\x12\x0e\n\x06job_id\x18\x01 \x01(\t\"=\n\x0bJobResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0e\n\x06job_id\x18\x02 \x01(\t\x12\r\n\x05\x65rror\x18\x03 \x01(\t\"\x0f\n\rStatusRequest\">\n\x0eStatusResponse\x12\x13\n\x0b\x61\x63tive_jobs\x18\x01 \x01(\r\x12\x17\n\x0f\x62ytes_processed\x18\x02 \x01(\x04\"\x0f\n\rHealthRequest\"1\n\x0eHealthResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07version\x18\x02 \x01(\t2\x8b\x03\n\tReelForge\x12>\n\x0bStartEncode\x12\x17.reelforge.EncodeConfig\x1a\x16.reelforge.JobResponse\x12;\n\nStopEncode\x12\x15.reelforge.JobRequest\x1a\x16.reelforge.JobResponse\x12>\n\x0bStartDecode\x12\x17.reelforge.DecodeConfig\x1a\x16.reelforge.JobResponse\x12;\n\nStopDecode\x12\x15.reelforge.JobRequest\x1a\x16.reelforge.JobResponse\x12@\n\tGetStatus\x12\x18.reelforge.StatusRequest\x1a\x19.reelforge.StatusResponse\x12\x42\n\x0bHealthCheck\x12\x18.reelforge.HealthRequest\x1a\x19.reelforge.HealthResponseb\x06proto3')
)




_ENCODECONFIG = _descriptor.Descriptor(
  name='EncodeConfig',
  full_name='reelforge.EncodeConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='codec', full_name='reelforge.EncodeConfig.codec', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='width', full_name='reelforge.EncodeConfig.width', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='height', full_name='reelforge.EncodeConfig.height', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bitrate', full_name='reelforge.EncodeConfig.bitrate', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fps', full_name='reelforge.EncodeConfig.fps', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=31,
  serialized_end=121,
)


_DECODECONFIG = _descriptor.Descriptor(
  name='DecodeConfig',
  full_name='reelforge.DecodeConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='codec', full_name='reelforge.DecodeConfig.codec', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='width', full_name='reelforge.DecodeConfig.width', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='height', full_name='reelforge.DecodeConfig.height', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=123,
  serialized_end=183,
)


_JOBREQUEST = _descriptor.Descriptor(
  name='JobRequest',
  full_name='reelforge.JobRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='job_id', full_name='reelforge.JobRequest.job_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=185,
  serialized_end=213,
)


_JOBRESPONSE = _descriptor.Descriptor(
  name='JobResponse',
  full_name='reelforge.JobResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='reelforge.JobResponse.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='job_id', full_name='reelforge.JobResponse.job_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='error', full_name='reelforge.JobResponse.error', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=215,
  serialized_end=276,
)


_STATUSREQUEST = _descriptor.Descriptor(
  name='StatusRequest',
  full_name='reelforge.StatusRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=278,
  serialized_end=293,
)


_STATUSRESPONSE = _descriptor.Descriptor(
  name='StatusResponse',
  full_name='reelforge.StatusResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='active_jobs', full_name='reelforge.StatusResponse.active_jobs', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bytes_processed', full_name='reelforge.StatusResponse.bytes_processed', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=295,
  serialized_end=357,
)


_HEALTHREQUEST = _descriptor.Descriptor(
  name='HealthRequest',
  full_name='reelforge.HealthRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=359,
  serialized_end=374,
)


_HEALTHRESPONSE = _descriptor.Descriptor(
  name='HealthResponse',
  full_name='reelforge.HealthResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='reelforge.HealthResponse.status', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='version', full_name='reelforge.HealthResponse.version', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=376,
  serialized_end=425,
)

DESCRIPTOR.message_types_by_name['EncodeConfig'] = _ENCODECONFIG
DESCRIPTOR.message_types_by_name['DecodeConfig'] = _DECODECONFIG
DESCRIPTOR.message_types_by_name['JobRequest'] = _JOBREQUEST
DESCRIPTOR.message_types_by_name['JobResponse'] = _JOBRESPONSE
DESCRIPTOR.message_types_by_name['StatusRequest'] = _STATUSREQUEST
DESCRIPTOR.message_types_by_name['StatusResponse'] = _STATUSRESPONSE
DESCRIPTOR.message_types_by_name['HealthRequest'] = _HEALTHREQUEST
DESCRIPTOR.message_types_by_name['HealthResponse'] = _HEALTHRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

EncodeConfig = _reflection.GeneratedProtocolMessageType('EncodeConfig', (_message.Message,), dict(
  DESCRIPTOR = _ENCODECONFIG,
  __module__ = 'reel_forge_pb2'
  # @@protoc_insertion_point(class_scope:reelforge.EncodeConfig)
  ))
_sym_db.RegisterMessage(EncodeConfig)

DecodeConfig = _reflection.GeneratedProtocolMessageType('DecodeConfig', (_message.Message,), dict(
  DESCRIPTOR = _DECODECONFIG,
  __module__ = 'reel_forge_pb2'
  # @@protoc_insertion_point(class_scope:reelforge.DecodeConfig)
  ))
_sym_db.RegisterMessage(DecodeConfig)

JobRequest = _reflection.GeneratedProtocolMessageType('JobRequest', (_message.Message,), dict(
  DESCRIPTOR = _JOBREQUEST,
  __module__ = 'reel_forge_pb2'
  # @@protoc_insertion_point(class_scope:reelforge.JobRequest)
  ))
_sym_db.RegisterMessage(JobRequest)

JobResponse = _reflection.GeneratedProtocolMessageType('JobResponse', (_message.Message,), dict(
  DESCRIPTOR = _JOBRESPONSE,
  __module__ = 'reel_forge_pb2'
  # @@protoc_insertion_point(class_scope:reelforge.JobResponse)
  ))
_sym_db.RegisterMessage(JobResponse)

StatusRequest = _reflection.GeneratedProtocolMessageType('StatusRequest', (_message.Message,), dict(
  DESCRIPTOR = _STATUSREQUEST,
  __module__ = 'reel_forge_pb2'
  # @@protoc_insertion_point(class_scope:reelforge.StatusRequest)
  ))
_sym_db.RegisterMessage(StatusRequest)

StatusResponse = _reflection.GeneratedProtocolMessageType('StatusResponse', (_message.Message,), dict(
  DESCRIPTOR = _STATUSRESPONSE,
  __module__ = 'reel_forge_pb2'
  # @@protoc_insertion_point(class_scope:reelforge.StatusResponse)
  ))
_sym_db.RegisterMessage(StatusResponse)

HealthRequest = _reflection.GeneratedProtocolMessageType('HealthRequest', (_message.Message,), dict(
  DESCRIPTOR = _HEALTHREQUEST,
  __module__ = 'reel_forge_pb2'
  # @@protoc_insertion_point(class_scope:reelforge.HealthRequest)
  ))
_sym_db.RegisterMessage(HealthRequest)

HealthResponse = _reflection.GeneratedProtocolMessageType('HealthResponse', (_message.Message,), dict(
  DESCRIPTOR = _HEALTHRESPONSE,
  __module__ = 'reel_forge_pb2'
  # @@protoc_insertion_point(class_scope:reelforge.HealthResponse)
  ))
_sym_db.RegisterMessage(HealthResponse)



_REELFORGE = _descriptor.ServiceDescriptor(
  name='ReelForge',
  full_name='reelforge.ReelForge',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=428,
  serialized_end=823,
  methods=[
  _descriptor.MethodDescriptor(
    name='StartEncode',
    full_name='reelforge.ReelForge.StartEncode',
    index=0,
    containing_service=None,
    input_type=_ENCODECONFIG,
    output_type=_JOBRESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='StopEncode',
    full_name='reelforge.ReelForge.StopEncode',
    index=1,
    containing_service=None,
    input_type=_JOBREQUEST,
    output_type=_JOBRESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='StartDecode',
    full_name='reelforge.ReelForge.StartDecode',
    index=2,
    containing_service=None,
    input_type=_DECODECONFIG,
    output_type=_JOBRESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='StopDecode',
    full_name='reelforge.ReelForge.StopDecode',
    index=3,
    containing_service=None,
    input_type=_JOBREQUEST,
    output_type=_JOBRESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetStatus',
    full_name='reelforge.ReelForge.GetStatus',
    index=4,
    containing_service=None,
    input_type=_STATUSREQUEST,
    output_type=_STATUSRESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='HealthCheck',
    full_name='reelforge.ReelForge.HealthCheck',
    index=5,
    containing_service=None,
    input_type=_HEALTHREQUEST,
    output_type=_HEALTHRESPONSE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_REELFORGE)

DESCRIPTOR.services_by_name['ReelForge'] = _REELFORGE

# @@protoc_insertion_point(module_scope)
