# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from src.client import reel_forge_pb2 as reel__forge__pb2


class ReelForgeStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.StartEncode = channel.unary_unary(
        '/reelforge.ReelForge/StartEncode',
        request_serializer=reel__forge__pb2.EncodeConfig.SerializeToString,
        response_deserializer=reel__forge__pb2.JobResponse.FromString,
        )
    self.StopEncode = channel.unary_unary(
        '/reelforge.ReelForge/StopEncode',
        request_serializer=reel__forge__pb2.JobRequest.SerializeToString,
        response_deserializer=reel__forge__pb2.JobResponse.FromString,
        )
    self.StartDecode = channel.unary_unary(
        '/reelforge.ReelForge/StartDecode',
        request_serializer=reel__forge__pb2.DecodeConfig.SerializeToString,
        response_deserializer=reel__forge__pb2.JobResponse.FromString,
        )
    self.StopDecode = channel.unary_unary(
        '/reelforge.ReelForge/StopDecode',
        request_serializer=reel__forge__pb2.JobRequest.SerializeToString,
        response_deserializer=reel__forge__pb2.JobResponse.FromString,
        )
    self.GetStatus = channel.unary_unary(
        '/reelforge.ReelForge/GetStatus',
        request_serializer=reel__forge__pb2.StatusRequest.SerializeToString,
        response_deserializer=reel__forge__pb2.StatusResponse.FromString,
        )
    self.HealthCheck = channel.unary_unary(
        '/reelforge.ReelForge/HealthCheck',
        request_serializer=reel__forge__pb2.HealthRequest.SerializeToString,
        response_deserializer=reel__forge__pb2.HealthResponse.FromString,
        )


class ReelForgeServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def StartEncode(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def StopEncode(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def StartDecode(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def StopDecode(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetStatus(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def HealthCheck(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ReelForgeServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'StartEncode': grpc.unary_unary_rpc_method_handler(
          servicer.StartEncode,
          request_deserializer=reel__forge__pb2.EncodeConfig.FromString,
          response_serializer=reel__forge__pb2.JobResponse.SerializeToString,
      ),
      'StopEncode': grpc.unary_unary_rpc_method_handler(
          servicer.StopEncode,
          request_deserializer=reel__forge__pb2.JobRequest.FromString,
          response_serializer=reel__forge__pb2.JobResponse.SerializeToString,
      ),
      'StartDecode': grpc.unary_unary_rpc_method_handler(
          servicer.StartDecode,
          request_deserializer=reel__forge__pb2.DecodeConfig.FromString,
          response_serializer=reel__forge__pb2.JobResponse.SerializeToString,
      ),
      'StopDecode': grpc.unary_unary_rpc_method_handler(
          servicer.StopDecode,
          request_deserializer=reel__forge__pb2.JobRequest.FromString,
          response_serializer=reel__forge__pb2.JobResponse.SerializeToString,
      ),
      'GetStatus': grpc.unary_unary_rpc_method_handler(
          servicer.GetStatus,
          request_deserializer=reel__forge__pb2.StatusRequest.FromString,
          response_serializer=reel__forge__pb2.StatusResponse.SerializeToString,
      ),
      'HealthCheck': grpc.unary_unary_rpc_method_handler(
          servicer.HealthCheck,
          request_deserializer=reel__forge__pb2.HealthRequest.FromString,
          response_serializer=reel__forge__pb2.HealthResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'reelforge.ReelForge', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
